---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fake-smtp
  name: fake-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-smtp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fake-smtp
    spec:
      containers:
      - image: brokenpip3/fake-smtp:2
        name: fake-smtp
        ports:
        - containerPort: 10025
          protocol: TCP
        resources: {}
        #env:
        #- name: "NOLOG"
        #  value: "1"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fake-smtp
  name: fake-smtp
spec:
  ports:
  - name: "10025"
    port: 10025
    protocol: TCP
    targetPort: 10025
  selector:
    app: fake-smtp
  type: ClusterIP
---
